name: basic workflow
on: workflow_dispatch
jobs:
  basic-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "Hello world!"
      - name: Show date
        run: date
      - name: Print goodbye
        run: echo "Done - bye!"
